stages:
  - clean
  - build
  - test

clean:
  stage: clean
  script:
    - ./gradlew clean
  tags:
    - docker

build:
  stage: build
  script:
    - ./gradlew build
  tags:
    - docker
  artifacts:
    paths:
      - build/libs/

test:
  stage: test
  script:
    - ./gradlew test
  tags:
    - docker
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/TEST-*.xml