stages:
  - clean
  - build
  - test

clean-job:
  stage: clean
  script:
      - ./gradlew clean

compile:
  stage: build
  script:
    - ./gradlew :missionmodel:build --refresh-dependencies
    - ./gradlew scheduling:build
    - ./gradlew constraints:build

assemble-jars:
    stage: build
    script:
      - ./gradlew scheduling:buildAllProcedureJars
      - ./gradlew constraints:buildAllProcedureJars

junit-job:
  stage: test
  script:
    - ./gradlew :missionmodel:test
    - ./gradlew :constraints:test
    - ./gradlew :scheduling:test
